### ISSUE TITLE
Hi, can someone tells me how to get the file - "data_list" mentioned in the README? 

### ISSUE THREAD

**Issue by zhiwenfan** [XUSean0118/DVSNet#1]
Hi, when I search in the CityScape website, I could not find this file- "data_list". I am new to Video Segmentation, could someone helps me with this problem?

**Comment by XUSean0118** [comment]
Hi, "data_list" is a file which contains the input(images) files' name. If you download CityScapes dataset,  "data_list" is "eval_list.txt",  "test_list.txt"  and "train_list.txt" in "cityscapes_dataset/cityscape/list/".

**Comment by zhiwenfan** [comment]
@XUSean0118 
Thank you for your quick reply, I have found this file in your project ! 
But when I use the eval_list.txt for inference.py, I found the item of label path in list.txt such as munster_000007_000019_gtFine_labelTrainIds.png is not the same with the image name in CityScape datasets which is named munster_000007_000019_gtFine_labelIds.png. 
Could you please draw a little of your time to answer this simple question?

**Comment by XUSean0118** [comment]
You can use this "https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py" to convert labelIds to labelTrainIds and you can refer to the comment of the code for more details.

**Comment by zhiwenfan** [comment]
@XUSean0118  
Thank you for your generous help! Wish you have a good day!
