### ISSUE TITLE
images train list

### ISSUE THREAD

**Issue by AlexDenis** [XUSean0118/DVSNet#3]
Hi! 
I'm sorry for disturbing as it is more of a question than of an issue, but I guess this is the best place to ask :) 
I've been trying to train your model on my data and I wanted to be sure that I understand everything correctly - and I have a question about `imagestrain_13_list.txt`. Could you please explain what each column represents exactly? As far as I understand, the first column represents some sort of context (13 previous frames..? why 13? does it yield a better result than 20 frames mentioned in your paper?) for the image represented in the second column, and the third column is the segmentation of a corresponding image in the second column. How far am I from the truth? :) Thank you!

P.S. It would also be great if you could explain the indexing system, for example, what do 000172 (just a video id?) and 000014 (frame number?) mean in the following image: `leftImg8bit_sequence/train/bremen/bremen_000172_000014_leftImg8bit.png`
Also, what is the difference between `leftImg8bit/...` and `leftImg8bit_sequence/...` (same stuff after /)?

**Comment by guojingsai** [comment]
Hi,
I try to get segmented results of vedio frames by python3 inference.py --data-dir=/data/leftImg8bit_demoVideo/leftImg8bit/ --data-list=/data/list ，but I encounted this problem
Traceback (most recent call last):
File "inference.py", line 12, in
from model import DeepLab_Fast, FlowNets, Decision
File "/data/model/init.py", line 1, in
from .deeplabmodel import DeepLab_Fast
File "/data/model/deeplabmodel.py", line 3, in
from network import DeepLab
ImportError: No module named 'network'
Could you tell me Why this problem,and then What changes should I make to solve this problem?
Thank you! @AlexDenis
