### ISSUE TITLE
ImportError: No module named 'network'

### ISSUE THREAD

**Issue by guojingsai** [XUSean0118/DVSNet#4]
Hi, 
    I try to get segmented results of vedio frames by python3 inference.py --data-dir=/data/leftImg8bit_demoVideo/leftImg8bit/ --data-list=/data/list ，but I encounted this problem 
Traceback (most recent call last):
  File "inference.py", line 12, in <module>
    from model import DeepLab_Fast, FlowNets, Decision
  File "/data/model/__init__.py", line 1, in <module>
    from .deeplabmodel import DeepLab_Fast
  File "/data/model/deeplabmodel.py", line 3, in <module>
    from network import DeepLab
ImportError: No module named 'network'
Could you tell me Why this problem,and then What changes should I make to solve this problem?
Thank you! @XUSean0118

**Comment by XUSean0118** [comment]
Hi, guojingsai
Please try to use  python 2.7 instead of you python3.
