### ISSUE TITLE
Questions about training on other dataset

### ISSUE THREAD

**Issue by qwenqw** [XUSean0118/DVSNet#6]
Hi, thanks for your sharing.
Now I want to train the DVSNet on my own dataset. But I am very confused about the finetune (segmentation + flow) model used in gentestcase.py. The finetune models are all in one checkpoint without decision network, but the codes are separate as DeepLabv2 and FlowNet2. 
How can I get the finetune model on my own dataset and train the DVSNet? could you give me some advice?Thanks very much

**Comment by XUSean0118** [comment]
Hi, qwrnqw
I train the model(flow + segmentation) in two step. First separately train DeepLabv2 and FlowNet2. Second finetune them together with fixed DeepLabv2. Isuggest you finetune your data in second step.

**Comment by qwenqw** [comment]
@XUSean0118 Thank you for replying. I notice that the file(deeplabmodel.py)  is as same as tensorflow-deeplab-resnet. What  does the fixed Deeplabv2 mean? Can you share more about it ?

**Comment by XUSean0118** [comment]
@qwenqw In first step, I use pre-train Deeplabv2 and finetune it with cityscapes dataset. Then combine it with pre-train Flownet2. In second step, I train the layers of Flownet2 part with fixed Deeplabv2 part. If your data have other classes, you should go through two steps. Otherwise, only go through second steps for different datas with same class as cityscapes dataset.

**Comment by qwenqw** [comment]
@XUSean0118 Sorry to bother you again. I try to read the model from .meta file. The results as follows. And I also get what you mean. The Deeplabv2 model need to be frozen after finetuned. And then it is combined with Flownet2. But I am new to tensorflow,  I cannot find the right way to complete this. I would appreciate it if you would help me complete it.
![image](https://user-images.githubusercontent.com/23628614/49220203-8d2d2400-f410-11e8-9522-0d3b6742275f.png)

**Comment by XUSean0118** [comment]
@qwenqw 
You can try this code to extract flownet variables and train them.
trainable = [v for v in tf.global_variables() if "FlowNets" in v.name]
